//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPSB_DBMS.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string Conclusion { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
